DROP VIEW IF EXISTS view_mapped_permissions_production;
DROP VIEW IF EXISTS view_mapped_permissions_staging;
DROP VIEW IF EXISTS view_mapped_permissions;
DROP VIEW IF EXISTS view_partial_app_info;
DROP VIEW IF EXISTS view_function_group_info;
DROP VIEW IF EXISTS view_module_config;
DROP VIEW IF EXISTS view_message_text_production;
DROP VIEW IF EXISTS view_message_text_staging;
DROP VIEW IF EXISTS view_message_group_production;
DROP VIEW IF EXISTS view_message_group_staging;
DROP TABLE IF EXISTS message_group CASCADE;
DROP TABLE IF EXISTS hmi_level_conversion;
DROP TABLE IF EXISTS app_auto_approval;
DROP TABLE IF EXISTS forgot_password_hash;
DROP TABLE IF EXISTS user_accounts;
DROP TABLE IF EXISTS function_group_parameters;
DROP TABLE IF EXISTS function_group_hmi_levels;
