version: "3.9"
services:
  server:
    build:
      context: .
      args:
        - VERSION=master
    ports:
      - "3000:3000"
    volumes:
      - data:/usr/policy
    env_file:
      - .env
    links:
      - redis
      - postgres
    depends_on:
      - redis
      - postgres
    command: ["./wait-for-it.sh", "postgres:5432", "--", "npm", "start"]
  redis:
    image: redis
  postgres:
    image: postgres:10.19-bullseye
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_DATABASE}"
volumes:
  data: